source "https://rubygems.org"

gem "ruby_wasm", "~> 2.10.1"
gem "js", "~> 2.10.1"

[
  ["webvas", ".."],
  ["larb", "../../larb"],
  ["rbgl", "../../rbgl"],
  ["tessel", "../../tessel"]
].each do |name, relative_path|
  path = File.expand_path(relative_path, __dir__)
  if File.file?(File.join(path, "#{name}.gemspec"))
    gem name, path: path
  else
    gem name
  end
end
