source "https://rubygems.org"

gem "ruby_wasm", "~> 2.10.1"
gem "js", "~> 2.10.1"

gem "webvas", path: ".."
gem "larb", ">= 1.0.2"
gem "rbgl"
gem "tessel"
gem "gesso", ">= 0.2.1"
gem "glyphic"
gem "rlsl"
